### ISSUE TITLE
extra 8 ball jest test have error

### ISSUE THREAD

**Issue by ali-nasir-ali** [CodeYourFuture/JavaScript-Core-1-Coursework-Week1#477]
I believe there is something wrong with the extra 8 ball test part.
when I run it with the same code in a separate file with out jest test it runs fine and gave me the four moods ( very positive, positive , ... ) but with the jest test on the file it prints out the log file with numbers instead of the moods.

------------------
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> javascript-core-1-coursework-week1@1.0.0 test
> jest "--testPathPattern" ".\\extra\\3-magic-8-ball.js"

 FAIL   extra  extra/3-magic-8-ball.js
  × whole magic 8 ball sequence (21 ms)
  √ magic 8 ball returns different values each time (23 ms)
  × checkAnswer works for `It is decidedly so.` (3 ms)
  × checkAnswer works for `My reply is no.` (2 ms)

  ● whole magic 8 ball sequence

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 3

      130 |   expect(typeof answer).toEqual("string");
      131 |
    > 132 |   expect(consoleLogSpy).toHaveBeenCalledTimes(1);
          |                         ^
      133 |   expect(consoleLogSpy).toHaveBeenLastCalledWith("The ball has shaken!");
      134 |
      135 |   expect(checkAnswer(answer)).toBeOneOf([

      at Object.<anonymous> (extra/3-magic-8-ball.js:132:25)

  ● checkAnswer works for `It is decidedly so.`

    expect(received).toEqual(expected) // deep equality

    Expected: "very positive"
    Received: "l"

      163 |
      164 | test("checkAnswer works for `It is decidedly so.`", () => {
    > 165 |   expect(checkAnswer("It is decidedly so.")).toEqual("very positive");
          |                                              ^
      166 | });
      167 |
      168 | test("checkAnswer works for `My reply is no.`", () => {

      at Object.<anonymous> (extra/3-magic-8-ball.js:165:46)

  ● checkAnswer works for `My reply is no.`

    expect(received).toEqual(expected) // deep equality

    Expected: "very negative"
    Received: " "

      167 |
      168 | test("checkAnswer works for `My reply is no.`", () => {
    > 169 |   expect(checkAnswer("My reply is no.")).toEqual("very negative");
          |                                          ^
      170 | });
      171 |

      at Object.<anonymous> (extra/3-magic-8-ball.js:169:42)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Without a doubt.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  negative

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Better not tell you now.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Yes - definitely.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    As I see it, yes.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very negative

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Don't count on it.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very negative

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    My reply is no.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Yes - definitely.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    It is certain.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Outlook good.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very positive

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    Yes - definitely.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    The ball has shaken!

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  very negative

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
    My reply is no.

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  0

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  11

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  2

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  15

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  7

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  12

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)
          at Array.map (<anonymous>)

  console.log
      The answer is :  9

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log
      The answer is :  13
      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

  console.log

      at console.<anonymous> (node_modules/jest-mock/build/index.js:845:25)

Tests:       3 failed, 1 passed, 4 total
Snapshots:   0 total
Time:        1.315 s

---------------------------------------------------

when i ran the same program on a saparate file with for loop in 1000 intervals it gave me the moods right.
  The answer is :  very positive
  The answer is :  negative
  The answer is :  very negative
  The answer is :  negative
  The answer is :  very negative
  The answer is :  very negative
  The answer is :  very negative
  The answer is :  positive
  The answer is :  negative
  The answer is :  positive
  The answer is :  very positive
  The answer is :  very negative
  The answer is :  very positive
  The answer is :  negative
  The answer is :  positive
  The answer is :  very negative
  The answer is :  positive
  The answer is :  very negative
  The answer is :  very positive
  The answer is :  very positive
  The answer is :  very positive
  The answer is :  positive
  The answer is :  positive
  The answer is :  very positive
  The answer is :  very negative
  The answer is :  very positive
  The answer is :  negative
  The answer is :  very positive
  The answer is :  very negative

**Comment by Dedekind561** [comment]
Hello there,
Thank you for raising this question. I think our tests are working at the moment - think you need to double check your current implementation of the magic 8 ball problem. I've left a comment on your PR.
